Beta second deploy (#230)
* feat: missed a state in SP, some comments

* feat: updated tomb build

* fix: remove random debug statement

* fix: changed types for key management (#163)

* feat: fresh build of tomb from main

* feat: start deploying to beta

* chore: clean up service names

* feat: tweaks to deployment configs

* feat: unecessary feature

* feat: fight the deployment

* fix: frontend service name

* feat: need to use the entire directory now for the build unfortunately, guess that give better cacheing though

* fix: whoops left in a bit of a merge conflict

* fix: also fix the staging service

* chore: fresh wasm build, straight from main

* feat: just do automatic key generation

* fix: merge conflict

* fix: error types

* fix: duplicate error use

* fix: weird rebuild always happening in staging

* feat: better error handling on env reset

* feat: allow dry runs of build and deploy script

* fix: reset environment with key paths{

* fix: also deploy the built frontend

* feat: add dry run to staging deploy

* feat: restore parent docker building

* fix: staging service is now deployable again

* fix: storage provider isn't auto-deployed

* fix: rsync

* feat: remove file that slipped in from a merge conflict

* fix: clear out dist directory before building to limit what gets deployed

* fix: keep important files, ensure deps exist for the frontend

* fix: don't try to override deployed attributes and permissions

* fix: deployment issues

* fix: include dist

* fix: port mapping

* feat: try to work around localhost hardcoding

* fix: BAD BAD hardcoded localhost breaking production

* feat: fix service name in staging

* chore: update key names to match the other services

* chore: fresh build of banyan-cli

* chore: clean up, move yarn build before container

* feat: checkpoint for branch switching, test harnesses for upload reporting

* feat: test harnesses, and coverage over some metadata

* feat: reorganization and simplification

* fix: protect the active metadata

* fix: revert the hardcoded variables so this branch can be merged

* feat: update the wasm package to the newest main build

* fix: use correct verification key

* fix: lints

* fix: clippy lints

* feat: fix name in .env.sample

---------

Co-authored-by: Vlad Dezhniuk <77901473+vladdezhniuk@users.noreply.github.com>

diff --git a/crates/banyan-staging-service/bin/build_and_deploy b/crates/banyan-staging-service/bin/build_and_deploy
--- a/crates/banyan-staging-service/bin/build_and_deploy
+++ b/crates/banyan-staging-service/bin/build_and_deploy
@@ -8,10 +8,11 @@ cd $(dirname %0)
 DEPLOY_HOST="distributor.data.banyan.computer"
 DEPLOY_BASE_FOLDER="containers"
 
-SERVICE_NAME="${1:-banyan-staging-service}"
+DRY_RUN="${DRY_RUN:-0}"
+
+SERVICE_NAME="${1:-distributor-banyan}"
 SERVICE_PORT="${2:-3000}"
-SERVICE_ARGUMENTS="--auth-key /data/platform-auth.key --hostname https://${DEPLOY_HOST}/ --verifier-key /data/platform-verifier.public --upload-dir /data/uploads --platform-url https://api.data.banyan.computer"
-SERVICE_FEATURES="postgres"
+SERVICE_ARGUMENTS="--service-key-path /data/service-key.private --service-hostname https://${DEPLOY_HOST}/ --platform-public-key-path /data/platform-key.public --upload-dir /data/uploads --platform-hostname https://api.data.banyan.computer --service-name ${SERVICE_NAME}"
 
 # Everything beyond this point isn't expected to be changed between services
 
@@ -27,8 +28,8 @@ DEPLOY_SERVICE_DIRECTORY="${DEPLOY_BASE_FOLDER}/services"
 DEPLOY_STATE="${DEPLOY_BASE_FOLDER}/state"
 
 if ! git diff-index --quiet HEAD -- || ! git diff-files --quiet; then
-  echo "!!> Branch is dirty, can't build and deploy from this branch"
-  exit 1
+	echo "!!> Branch is dirty, can't build and deploy from this branch"
+	exit 1
 fi
 
 COMMIT_ID="$(git describe --always --dirty --long --tags)"
@@ -41,26 +42,31 @@ FULL_IMAGE_NAME="${ORG}/${NAMESPACE}/${IMAGE}:${COMMIT_ID}"
 TMP_IMAGE="$(mktemp /tmp/${SERVICE_NAME}.XXXXX.tar)"
 
 CONTAINER_RUNTIME="podman"
-if which docker &> /dev/null; then
-  CONTAINER_RUNTIME="docker"
+if which docker &>/dev/null; then
+	CONTAINER_RUNTIME="docker"
 fi
 
 # Create the actual container
-cp -f ../../Cargo.lock ./
-${CONTAINER_RUNTIME} build -t ${FULL_IMAGE_NAME} \
-  --build-arg CI_BUILD_REF=${COMMIT_ID} \
-  --build-arg FEATURES=${SERVICE_FEATURES} \
-  --build-arg SERVICE_NAME=${SERVICE_NAME} .
-rm -f Cargo.lock
+(
+	cd ../..
+	${CONTAINER_RUNTIME} build -t ${FULL_IMAGE_NAME} \
+		--build-arg CI_BUILD_REF=${COMMIT_ID} \
+		--build-arg CRATE_NAME=banyan-staging-service .
+)
 
 ${CONTAINER_RUNTIME} save -o ${TMP_IMAGE} ${FULL_IMAGE_NAME} &>/dev/null
 
 echo '==> Image successfully built and exported'
 
+if [ "${DRY_RUN}" = "1" ]; then
+	echo "Dry run completed successfully"
+	exit 0
+fi
+
 TMP_SERVICE="$(mktemp /tmp/${SERVICE_NAME}.XXXXX.service)"
 VERSIONED_SVC_NAME="${SERVICE_NAME}-${TIMESTAMP}-${COMMIT_ID}"
 
-cat << EOF > ${TMP_SERVICE}
+cat <<EOF >${TMP_SERVICE}
 [Unit]
 Description=${SERVICE_NAME}
 After=network-online.target
@@ -72,7 +78,7 @@ Restart=on-failure
 TimeoutStopSec=35
 ExecStartPre=rm -f %t/%n-pid %t/%n-cid
 ExecStartPre=podman load --input \${HOME}/${DEPLOY_IMAGE_ARCHIVE}/${IMAGE_BASE_NAME}.tar
-ExecStart=podman run -d --name ${SERVICE_NAME} --read-only --replace --restart=on-failure:3 --env-file \${HOME}/${DEPLOY_ENV}/${SERVICE_NAME} --mount type=bind,src=\${HOME}/${DEPLOY_PERSISTENT_DATA}/${SERVICE_NAME},dst=/data --userns keep-id:uid=65532,gid=65532 --network slirp4netns:allow_host_loopback=true --log-driver=k8s-file --log-opt max-size=128kb,path=\${HOME}/${DEPLOY_LOGS}/${SERVICE_NAME}.log --hostname ${SERVICE_NAME}.svc.${DEPLOY_HOST} --publish ${SERVICE_PORT}:3000/tcp --conmon-pidfile %t/%n-pid --cidfile %t/%n-cid ${FULL_IMAGE_NAME} ${SERVICE_ARGUMENTS}
+ExecStart=podman run -d --name ${SERVICE_NAME} --read-only --replace --restart=on-failure:3 --env-file \${HOME}/${DEPLOY_ENV}/${SERVICE_NAME} --mount type=bind,src=\${HOME}/${DEPLOY_PERSISTENT_DATA}/${SERVICE_NAME},dst=/data --userns keep-id:uid=65532,gid=65532 --network slirp4netns:allow_host_loopback=true --log-driver=k8s-file --log-opt max-size=128kb,path=\${HOME}/${DEPLOY_LOGS}/${SERVICE_NAME}.log --hostname ${SERVICE_NAME}.svc.${DEPLOY_HOST} --publish ${SERVICE_PORT}:3002/tcp --conmon-pidfile %t/%n-pid --cidfile %t/%n-cid ${FULL_IMAGE_NAME} ${SERVICE_ARGUMENTS}
 # If we want to replicate the k8s behavior wait-drain-and-shutdown, this is what we'd use to stop the service
 #ExecStop=podman stop -t 30 --cidfile %t/%n-cid
 # These servers don't have alternate services picking up its downtime so we want to take the fast restart path
